# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-15 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190514_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='pages',
            field=models.SmallIntegerField(default=5, verbose_name='分页数'),
        ),
    ]
