# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-15 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190515_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '文章分类', 'verbose_name_plural': '文章分类'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': '友情链接', 'verbose_name_plural': '友情链接'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': '文章系列', 'verbose_name_plural': '文章系列'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': '设置', 'verbose_name_plural': '设置'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '文章标签', 'verbose_name_plural': '文章标签'},
        ),
    ]
