# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-15 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190515_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, help_text='可为空', max_length=200, verbose_name='预览'),
        ),
        migrations.AlterField(
            model_name='post',
            name='series',
            field=models.ForeignKey(blank=True, help_text='可为空', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Series', verbose_name='系列'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=70, unique=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='名称'),
        ),
    ]
