# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-16 01:46
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190516_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='博主信息'),
        ),
    ]
