# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-16 01:49
from __future__ import unicode_literals

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190516_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='body',
            field=mdeditor.fields.MDTextField(verbose_name='博主信息'),
        ),
    ]
