# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-26 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_notice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_time'], 'verbose_name': '文章分类', 'verbose_name_plural': '文章分类'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-add_time'], 'verbose_name': '友情链接', 'verbose_name_plural': '友情链接'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-add_time'], 'verbose_name': '公告', 'verbose_name_plural': '公告'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['-created_time'], 'verbose_name': '文章系列', 'verbose_name_plural': '文章系列'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-created_time'], 'verbose_name': '文章标签', 'verbose_name_plural': '文章标签'},
        ),
        migrations.AddField(
            model_name='notice',
            name='status',
            field=models.CharField(choices=[('0', '显示'), ('1', '不显示')], default=0, max_length=1, verbose_name='是否显示'),
        ),
    ]
