# Generated by Django 2.2.3 on 2019-07-09 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190709_0927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': '友情链接', 'verbose_name_plural': '友情链接'},
        ),
        migrations.RenameField(
            model_name='link',
            old_name='add_time',
            new_name='created_time',
        ),
    ]
