# Generated by Django 2.2.3 on 2019-07-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20190709_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_status',
            field=models.SmallIntegerField(choices=[(0, '可评论'), (1, '不可评论')], default=0, verbose_name='评论状态'),
        ),
    ]
