# Generated by Django 2.2.3 on 2019-07-10 01:44

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_post_comment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', mdeditor.fields.MDTextField(verbose_name='博主信息')),
                ('pages', models.SmallIntegerField(default=5, verbose_name='文章分页数')),
                ('post_pic', models.SmallIntegerField(default=1, verbose_name='文章随机图片')),
            ],
            options={
                'verbose_name': '设置2',
                'verbose_name_plural': '设置2',
            },
        ),
    ]
