# Generated by Django 2.2.3 on 2019-07-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_setting2'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='post_pic',
            field=models.SmallIntegerField(default=1, verbose_name='文章随机图片'),
        ),
    ]
