# Generated by Django 2.2.3 on 2019-07-10 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_setting_post_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting2',
        ),
    ]
